# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'action_mailer'
require 'rails'
require 'sendgrid_events'
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  config.after(:all) do # Force a reset of some Classes
    project_dir = ENV['BUNDLE_GEMFILE'].split('/')
    project_dir.delete_at(-1)
    project_dir = project_dir.join('/')
    singletons.each do |s|
      Scribbler.send(:remove_const, s)
      load "#{project_dir}/lib/sendgrid_events/#{s.downcase}.rb"
    end
  end
end
