# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'action_mailer'
require 'rails'
require 'sqlite3'
require 'active_record'
require 'enumerated_field'

ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => ':memory:'
ActiveRecord::Schema.define do
  create_table :sendgrid_email_records, :force => true do |t|
    t.string :status
    t.string :to
    t.string :from
    t.string :subject

    t.timestamps
  end
end

Dir.glob(File.expand_path('../../app/models/**/*.rb', __FILE__)).each { |file| require file }
require 'sendgrid_events'

RSpec.configure do |config|

  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
